apiVersion: v1
kind: Secret
metadata:
  name: mcp-gateway-secrets
type: Opaque
stringData:
  GRAFANA_API_KEY: GRAFANA_API_KEY
  GRAFANA_URL: GRAFANA_URL
  mcp.env: |
    GRAFANA_API_KEY=GRAFANA_API_KEY
    grafana.api_key=GRAFANA_API_KEY