apiVersion: v1
kind: Secret
metadata:
  name: mcp-gateway-docker-config
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "DOCKER_API_KEY"
        }
      }
    }
