spring.application.name=ast-java-parser

server.port=8087

gitlab.base-url=https://gitlab.com/api/v4
gitlab.token=gitlab-pat
gitlab.clone-base-dir=./tmp/gitlab-repos
gitlab.clone-retention-ms=1800000
gitlab.cleanup-interval-ms=300000
