apiVersion: v1
kind: Service
metadata:
  name: mc-intra-drain3-service
  namespace: mc-intra
  labels:
    app: mc-intra-drain3-service
spec:
  selector:
    app: mc-intra-drain3-service
  ports:
    - name: http
      port: 8011
      targetPort: http
  type: ClusterIP
